-- category_id (structured, user-picked) and tags (free-text, AI-generated by
-- celebrate-phrase.js) are separate columns on purpose: category is a purely
-- additive concept, the existing AI tagging flow keeps working unmodified.
CREATE TABLE achievements (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  text        TEXT NOT NULL,
  category_id UUID NULL REFERENCES categories(id) ON DELETE SET NULL,
  tags        TEXT[] NOT NULL DEFAULT '{}',
  legacy_id   TEXT NULL UNIQUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_achievements_user_created ON achievements(user_id, created_at DESC);
CREATE INDEX idx_achievements_category ON achievements(category_id);
